data_path: "data/amazon_alexa.tsv"

preprocessing:
  lowercase: true
  remove_stopwords: true
  stem: true

features:
  max_features: 2500

train_test_split:
  test_size: 0.3
  random_state: 15

model:
  xgb:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.9
